
export const GET_ALL_OPPORTUNITIES = "GET_ALL_OPPORTUNITIES";
export const GET_ALL_APPLICATIONS = "GET_ALL_APPLICATIONS";
export const GET_ALL_EMPLOYERS = "GET_ALL_EMPLOYERS";
export const GET_ALL_INTERNS = "GET_ALL_INTERNS";
export const GET_ALL_INTERVIEWS = "GET_ALL_INTERVIEWS";
export const GET_ALL_SHORTLISTS = "GET_ALL_SHORTLISTS";
export const GET_ALL_SUBSCRIPTION_PLANS = "GET_ALL_SUBSCRIPTION_PLANS";
export const GET_ALL_TRANSACTIONS = "GET_ALL_TRANSACTIONS";
export const SERVER_ERROR = "SERVER_ERROR";